# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64a3bfc34ed0c03672e96b698bc01cb909c5c82715950938f65a4fd170ae0c5e542594507c1194b941102ebc70db1625f261d27275091cf863da11e431d6f33d

test:
  secret_key_base: 6b59466def5c3c0424ea09c89678e7aec33c62dd4c5e991d3c13c0ba6732b79e7621ff24b6badc63539b165efce2a6d29a753ddc5ec09ae47ab4af2f4adab177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
